iowa-b kubectl apply:
  variables:
    KUBE_CONFIG: /home/gitlab-runner/.kube/iowa-b.kubeconfig
  tags:
    - gcp
    - meao
  script:
    - echo $KUBE_CONFIG
    - kubectl_1.12  apply -f iowa-b/nucleus-dev/nucleus-dev-ns.yaml
    - kubectl_1.12 -n nucleus-dev apply -f iowa-b/nucleus-dev/deploy.yaml
    - kubectl_1.12 -n nucleus-dev apply -f iowa-b/nucleus-dev/svc.yaml
